### ISSUE TITLE
New installation failed - Table 'speedtest_tracker.cache' doesn't exist

### ISSUE THREAD

**Issue by ddluk** [alexjustesen/speedtest-tracker#2070]
**Describe the bug**
Default installation from documentation failed with error Table 'speedtest_tracker.cache' doesn't exist  

**To Reproduce**
1. Go to https://docs.speedtest-tracker.dev/getting-started/installation/using-docker-compose
2. Use docker compose for MariaDB database

> services:
    speedtest-tracker:
        image: lscr.io/linuxserver/speedtest-tracker:latest
        restart: unless-stopped
        container_name: speedtest-tracker
        ports:
            - 8080:80
            - 8443:443
        environment:
            - PUID=1000
            - PGID=1000
            - APP_KEY=valid key entered here
            - DB_CONNECTION=mariadb
            - DB_HOST=db
            - DB_PORT=3306
            - DB_DATABASE=speedtest_tracker
            - DB_USERNAME=speedtest_tracker
            - DB_PASSWORD=password
        volumes:
            - /path/to/data:/config
            - /path/to-custom-ssl-keys:/config/keys
        depends_on:
            - db
    db:
        image: mariadb:11
        restart: always
        environment:
            - MYSQL_DATABASE=speedtest_tracker
            - MYSQL_USER=speedtest_tracker
            - MYSQL_PASSWORD=password
            - MYSQL_RANDOM_ROOT_PASSWORD=true
        volumes:
            - speedtest-db:/var/lib/mysql
        healthcheck:
            test: ["CMD", "healthcheck.sh", "--connect", "--innodb_initialized"]
            interval: 5s
            retries: 3
            timeout: 5s
volumes:
  speedtest-db:

4. After container creation error appear:

`SQLSTATE[42S02]: Base table or view not found: 1146 Table 'speedtest_tracke  
  r.cache' doesn't exist `

**Logs**

#16 /app/www/vendor/laravel/framework/src/Illuminate/Container/Util.php(43): Illuminate\\Container\\BoundMethod::Illuminate\\Container\\{closure}()
#17 /app/www/vendor/laravel/framework/src/Illuminate/Container/BoundMethod.php(95): Illuminate\\Container\\Util::unwrapIfClosure()
#18 /app/www/vendor/laravel/framework/src/Illuminate/Container/BoundMethod.php(35): Illuminate\\Container\\BoundMethod::callBoundMethod()
#19 /app/www/vendor/laravel/framework/src/Illuminate/Container/Container.php(694): Illuminate\\Container\\BoundMethod::call()
#20 /app/www/vendor/laravel/framework/src/Illuminate/Console/Command.php(213): Illuminate\\Container\\Container->call()
#21 /app/www/vendor/symfony/console/Command/Command.php(279): Illuminate\\Console\\Command->execute()
#22 /app/www/vendor/laravel/framework/src/Illuminate/Console/Command.php(182): Symfony\\Component\\Console\\Command\\Command->run()
#23 /app/www/vendor/symfony/console/Application.php(1094): Illuminate\\Console\\Command->run()
#24 /app/www/vendor/symfony/console/Application.php(342): Symfony\\Component\\Console\\Application->doRunCommand()
#25 /app/www/vendor/symfony/console/Application.php(193): Symfony\\Component\\Console\\Application->doRun()
#26 /app/www/vendor/laravel/framework/src/Illuminate/Foundation/Console/Kernel.php(198): Symfony\\Component\\Console\\Application->run()
#27 /app/www/vendor/laravel/framework/src/Illuminate/Foundation/Application.php(1231): Illuminate\\Foundation\\Console\\Kernel->handle()
#28 /app/www/artisan(13): Illuminate\\Foundation\\Application->handleCommand()
#29 {main}
"} 
In Connection.php line 825:
                                                                               
  SQLSTATE[42S02]: Base table or view not found: 1146 Table 'speedtest_tracke  
  r.cache' doesn't exist (Connection: mariadb, SQL: select * from `cache` whe  
  re `key` in (laravel_cache_illuminate:queue:restart))                        
                                                                               
In Connection.php line 407:
                                                                               
  SQLSTATE[42S02]: Base table or view not found: 1146 Table 'speedtest_tracke  
  r.cache' doesn't exist

**Comment by alexjustesen** [comment]
Couple of things...

1. Don't forget you need to generate an `APP_KEY`
2. You should mount the volume `/path/to/data:/config` to somewhere on your host system
3. You can remove the volume mount `/path/to-custom-ssl-keys:/config/keys` if you're not using custom SSL certs

If you're still having issue after those changes let us know.

**Comment by ddluk** [comment]
Thanks for reply. 

1. I've got APP_KEY generated and added to docker compose file.
2. I've got mounted volume to my host system.
3. Removed because I'm not using custom SSL certs.

Issue is still happening.

**Comment by ddluk** [comment]
So I did some investigation and switched on APP_DEBUG to see the result and this is what I get:

`Class "App\Services\SystemChecker" not found

PHP 8.3.17 — Laravel 11.43.2
`

**Comment by alexjustesen** [comment]
That is fixed in `1.2.5` which LSIO will build here soon

**Comment by ddluk** [comment]
Ok, so I updated version to 1.2.5 but it was still not working. I set APP_DEBUG to true to check what's going on (container was redeployed) and then it suddenly started working properly which was strange. So this is what I found out:

Not working properly:

1.  Deploy containers using docker compose up
2. CTRL+C to stop working from console (I can also use docker compose up -d but it's easier to check logs at container deployment).
3. Start both db and app containers.

Working properly:

1.  Deploy containers using docker compose up
2. CTRL+C to stop working from console (I can also use docker compose up -d but it's easier to check logs at container deployment).
3. Start both db and app containers.
4. Restart app container when database is already running.

It look's like database container deployment is slower than application container starts so when application is already running and expecting working database to create application schema on database it's not able to do this. 

So in this scenario the best way will be to add following condition to docker compose:

> depends_on:
       db:
         condition: service_healthy


With that condition set application is starting in correct way and it's working properly.

> services:
    speedtest-tracker:
        image: lscr.io/linuxserver/speedtest-tracker:latest
        restart: unless-stopped
        container_name: speedtest-tracker
        ports:
            - 8080:80
            - 8443:443
        environment:
            - PUID=1000
            - PGID=1000
            - APP_KEY=base64:XXXXXXX
            - DB_CONNECTION=mariadb
            - DB_HOST=db
            - DB_PORT=3306
            - DB_DATABASE=speedtest_tracker
            - DB_USERNAME=speedtest_tracker
            - DB_PASSWORD=password
        volumes:
            - /home/ddluk/.docker_conf/SpeedtestTracker:/config
        **depends_on:
            db:
             condition: service_healthy**
    db:
        image: mariadb:11
        restart: always
        environment:
            - MYSQL_DATABASE=speedtest_tracker
            - MYSQL_USER=speedtest_tracker
            - MYSQL_PASSWORD=password
            - MYSQL_RANDOM_ROOT_PASSWORD=true
        volumes:
            - speedtest-db:/var/lib/mysql
        healthcheck:
            test: ["CMD", "healthcheck.sh", "--connect", "--innodb_initialized"]
            interval: 5s
            retries: 30
            timeout: 5s
volumes:
  speedtest-db:

**Comment by alexjustesen** [comment]
Let's override the default database cache, can you set `CACHE_STORE=file` in your environment variables. You can then restart the stack.

**Comment by alexjustesen** [comment]
Did you change the DB name, username or password after initially starting the application? This is starting to read more like the migrations didn't run on startup.

**Comment by ddluk** [comment]
No, I did't change anything, just started is as is. I don't know Laravel so much but from what I read it could be this. But from the other side with added condition to wait for db creation it's working properly.

**Comment by alexjustesen** [comment]
So you're all set now?

**Comment by ddluk** [comment]
Yes, I'm ok now. Do you think the documentation should be updated to reflect these changes in the docker-compose file?

**Comment by ncc0624** [comment]
I had the same error - however adding the healthy condition the problem was fixed. Just figured I'd throw my .02 in...
