### ISSUE TITLE
419 Page expired error

### ISSUE THREAD

**Issue by dhanuhammer** [alexjustesen/speedtest-tracker#2071]
**Describe the bug**
I installed this on my openwrt router on a Raspberry Pi 4, and it started to throw the 419 Page Expired error when trying to login with ipaddr:8990. But navigating to port 8943 works.

**Environment (please complete the following information):**
 - OS: Openwrt 24.10
-  Architecture: aarch64

.

**Comment by alexjustesen** [comment]
Make sure to follow https://docs.speedtest-tracker.dev/getting-started/installation, this error generally occurs when an `APP_KEY` isn't set.

If you continue to have issues also share your `docker-compose.yml` file.

**Comment by madamson747** [comment]
I'm having this issue as well.

I pulled the latest image and brought the container up and at first this didn't happen.
I re-created the container and now this error happens for me as well.

Before pulling the latest image it was working just fine. I even generated a new app key and updated my compose.yml file and that didn't fix it.

I'm running on a Ubuntu server (24.04.2) VM inside of Proxmox on an Intel i7 10th gen based system.

My speedtest-tracker portion of my compose.yml file:
`speedtest-tracker:
      container_name: speedtest-tracker
      ports:
          - 8082:80
          - 8444:443
      environment:
        - PUID=1000
        - PGID=1000
        - APP_NAME=speedTestTracker
        - APP_KEY=[new app key; removed for privacy]
        - DB_CONNECTION=pgsql
        - DB_HOST=${POSTGRES_DB_IP}
        - DB_PORT=5432
        - DB_DATABASE=speedtest_tracker
        - DB_USERNAME=postgres
        - DB_PASSWORD=[removed for privacy]
        - SPEEDTEST_SCHEDULE=0 * * * *
        - SPEEDTEST_SERVERS= [removed for privacy]
        - PRUNE_RESULTS_OLDER_THAN=180
        #- CHART_DATETIME_FORMAT= 
        #- DATETIME_FORMAT=
        - APP_TIMEZONE=America/Denver
        - DISPLAY_TIMEZONE=America/Denver
        - APP_DEBUG=true
      volumes:
        - ./speedTestTracker:/config
        #- /path/to-custom-ssl-keys:/config/keys
      image: lscr.io/linuxserver/speedtest-tracker:latest
      restart: unless-stopped
      depends_on:
        - adminPostgres
      networks:
        serverNetwork:
          ipv4_address: [removed for privacy]`

**Comment by PlasmaSoftUK** [comment]
I am also seeing this error on a setup that has been working fine for months, and also on a freshly setup new instance. I'm running it under Docker on macOS

**Comment by alexjustesen** [comment]
Did you change your `APP_KEY` after the initial setup?

**Comment by PlasmaSoftUK** [comment]
Yes I did, on both the one that's been running for months, and the fresh setup. Both have keys from the random generator website linked in the instructions.

**Comment by alexjustesen** [comment]
If that's the case then the error is because the `APP_KEY` is used for encryption which broke your stored password. 

You'll want to use the [command](https://docs.speedtest-tracker.dev/other/commands) `app:user-reset-password` which should fix the issue.

**Comment by PlasmaSoftUK** [comment]
I didn't do this. I didn't change it on the main one I've been running for months, other than at first install, and I'm still seeing these errors. I did change it on the fresh install, before I changed my password and still see the errors. This is not something I have changed, this happened after the docker container updated.

**Comment by PlasmaSoftUK** [comment]
I have done some more testing, I can log in and view the pages, but every 60 seconds the attached message pops up saying "Page has expired", I click OK, the message pops up again immediately, when I click OK for the second time it disappears for 60 seconds then shows again.

<img width="896" alt="Image" src="https://github.com/user-attachments/assets/1ad959ce-bc58-4ca1-b9f3-80f5921af847" />

This is happening on my months old install, and also a fresh install with just basic parameters changed.

**Comment by sirweazel** [comment]
I am also seeing this error (fresh setup).  Logged in, changed the default admin name, password, email.  I restarted the docker container several times and manually refreshed my web browser and everything worked. I didn't encounter the error until i closed/logged out of the browser and attempted to log back into the dashboard.  I'm going to reset my APP_KEY and delete my persistent volume and try again. I commented out the custom keys because I'm not using them.

```
services:
    speedtest-tracker:
        image: lscr.io/linuxserver/speedtest-tracker:latest
        restart: unless-stopped
        container_name: speedtest-tracker
        ports:
            - 8082:80
            - 8443:443
        environment:
            - PUID=1000
            - PGID=1000
            - APP_KEY=base64:4AnnIDoDS8i28gL32kOtqJZ66fT+neJhRnxrs1e9Xi4=
            - DB_CONNECTION=sqlite
            - APP_TIMEZONE=America/New_York
            - DISPLAY_TIMEZONE=America/New_York
            - SPEEDTEST_SCHEDULE=6 */2 * * *
        volumes:
            - /mnt/DataPool/speedtest-tracker-stack/config:/config
            #- /path/to-custom-ssl-keys:/config/keys
        healthcheck:
            test: curl -fSs APP_URL/api/healthcheck | jq -r .message || exit 1
            interval: 10s
            retries: 3
            start_period: 30s
            timeout: 10s
```

**Comment by Paronity** [comment]
> EDIT: I'll leave the below in case it helps anyone. But after some more testing, it appears FireFox didn't like the session cookie or site data. Clearing this resolved the issue. It seems like a cookie might be kept associated with the first login used and for whatever reason didn't refresh after the change.

This worked for me. My setup was working fine. Woke up the next day and it wasn't. Deleted the cookies from my browser related to the container and the issue went away.
