### ISSUE TITLE
disable login to set iframe on tablet

### ISSUE THREAD

**Issue by ZoXx** [alexjustesen/speedtest-tracker#752]
i am currently still using the old speedtesttracker from henry. This is integrated on my smarthome tablet as iframe and has the advantage that here no login is necessary.

is it planned that in your speedtesttracker the login is omitted. then this would be interesting for me. the login is not needed.

**Comment by alexjustesen** [comment]
Feature is planned to move the dashboard out of being behind authentication...

IMO setting and such should remain behind it.

**Comment by toxic0berliner** [comment]
I also need this, I have authelia in front and don't care to remember yet another username/password for something like this that doesn't seem critical in any way for me. The documentation speaks of an AUTH env var but it has no effect as of now.
Hope this gets changed

**Comment by alexjustesen** [comment]
> The documentation speaks of an AUTH env var but it has no effect as of now. Hope this gets changed

Can you link to where this is in the docs? Any reference to the old `AUTH` variable that didn't do anything should of been removed.

**Comment by toxic0berliner** [comment]
It's nowhere on your site or repo, I might have found it on someone else's repo whk gave a compose file for this

**Comment by ZoXx** [comment]
How to link the public dashboard?

**Comment by ZoXx** [comment]
I mean if i set anm iframe on tablet there is error "has refused the connection."

**Comment by ZoXx** [comment]
Error via Chrome: Refused to display XXXXX in a frame because it set 'X-Frame-Options' to 'sameorigin'.

**Comment by ZoXx** [comment]
Any news here. Would be nice to use this docker for my projects.

**Comment by alexjustesen** [comment]
Missed doing this: https://laravel.com/docs/10.x/csrf#csrf-excluding-uris

**Comment by ZoXx** [comment]
So it will be with the next release possible? :)

**Comment by alexjustesen** [comment]
> So it will be with the next release possible? :)

_maybe_

**Comment by ZoXx** [comment]
Good  morning :)
Update  was done, but next error message is here:
Refused to display 'XXXX' in a frame because it set multiple 'X-Frame-Options' headers with conflicting values ('ALLOW-FROM SAMEORIGIN, SAMEORIGIN'). Falling back to 'deny'.

**Comment by alexjustesen** [comment]
It's just happening on `/` and not any other URL right?

**Comment by ZoXx** [comment]
I have the Docker running on my Nas server.
My iobroker docker is also running there. the iframe is embedded in the vis (same ip address).

Embedded via iframe with the url: http://192.168.178.2:5008

**Comment by alexjustesen** [comment]
`v0.13.3` tagged and building, this should fix the duplicate `SAMEORIGIN` that was causing the issue

**Comment by ZoXx** [comment]
Nope :(

`Refused to display 'http://192.168.178.2:5008/' in a frame because it set 'X-Frame-Options' to 'sameorigin'.`

`Unchecked runtime.lastError: A listener indicated an asynchronous response by returning true, but the message channel closed before a response was received`

**Comment by alexjustesen** [comment]
It was in the PR as I haven't been able to update the docs yet but you'll need to set `ALLOW_EMBEDS=` to the domain your embedding in. Then it should work.

**Comment by ZoXx** [comment]
There are no settings for this in iobroker. Other iframes, websites etc run perfectly.

**Comment by alexjustesen** [comment]
> There are no settings for this in iobroker. Other iframes, websites etc run perfectly.

What's iobroker

**Comment by ZoXx** [comment]
https://hub.docker.com/r/buanet/iobroker

But that is not the problem. The problem is the iframe from speedtest.

**Comment by alexjustesen** [comment]
In speedtest tracker did you pass `ALLOW_EMBEDS=http://192.168.178.2` or with whatever your iobroker url is?

**Comment by ZoXx** [comment]
Here are my settings.
![image](https://github.com/alexjustesen/speedtest-tracker/assets/11578454/8950aa17-6164-405f-a17c-01a8b3d4f930)
![image](https://github.com/alexjustesen/speedtest-tracker/assets/11578454/547b3890-a761-4c04-b195-5ad9a2c54bd6)
![image](https://github.com/alexjustesen/speedtest-tracker/assets/11578454/c30de786-f2e6-43bd-9d17-842de3d1330c)

**Comment by marky421** [comment]
I am also getting this X-Frame-Options error. I use Nginx Proxy Manager to access speedtest-tracker via https://speedtest.mydomain.com, but now I am trying to integrate with Organizr as an iFrame tab pointing to my speedtest subdomain similar to what I have configured for Plex, Sonarr, Radarr, etc. I have tried setting `ALLOW_EMBEDs=http://<IP of Organizr host>` and I have also tried setting `APP_URL=https://speedtest.mydomain.com` but neither seem to have any affect. I don't have any issues opening https://speedtest.mydomain.com, it's only when I try opening it via an iFrame in Organizr that the X-Frame-Option error occurs.

For what it's worth, both speedtest-tracker and Organizr are running on the same docker host.

**Comment by marky421** [comment]
I was looking at this again today and while it still isn't working for me, I'm getting a slightly different error now:

`Refused to display 'https://speedtest.mydomain.io/' in a frame because it set multiple 'X-Frame-Options' headers with conflicting values ('ALLOW-FROM https://organizr.mydomain.io/, SAMEORIGIN'). Falling back to 'deny'.`

**Comment by alexjustesen** [comment]
I'm wondering if nginx is sending another header too, moving on from time zones so back to this later this week.

**Comment by alexjustesen** [comment]
If someone can give iframe a test again #1002 and #1003 should fix the issue, worked within my home lab for me.

Note: With how polling and filters are currently handled you might get a "page expired" error, I'm aware of that and will have a fix soon.

**Comment by marky421** [comment]
I was able to test this with the latest :dev release and it is now loading the page for me, but there is still an error being logged to the console regarding the X-Frame-Options:

`Invalid 'X-Frame-Options' header encountered when loading 'https://speedtest.mydomain.io/': 'ALLOW-FROM https://organizr.mydomain.io/' is not a recognized directive. The header will be ignored.`

Apparently the ALLOW-FROM directive is considered obsolete: https://developer.mozilla.org/en-US/docs/Web/HTTP/Headers/X-Frame-Options#allow-from_origin

Everthing does appear to be working as expected, but I'm not not sure if I should be worried about this error.

**Comment by alexjustesen** [comment]
You can probably ignore it for now, I know I need to replace it with content policy at some point but most browsers still support it. Now that this is "working" minus the big closing this issue..

**Comment by alexjustesen** [comment]
#1019 fixes the expired page warning, will be included in the next release.
